a.o:fake:(.text+0x0): undefined reference to `B::vf()'
a.o:fake:(.text+0x8): undefined reference to `D::vf()'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f00()'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0x95): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f00()'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f01(char)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xa1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f01(char)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f02(signed char)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xad): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f02(signed char)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f03(unsigned char)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xb9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f03(unsigned char)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f04(short)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xc6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f04(short)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f05(unsigned short)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xd3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f05(unsigned short)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f06(int)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xdf): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f06(int)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f07(unsigned int)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xeb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f07(unsigned int)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f08(long)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0xfa): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f08(long)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f09(unsigned long)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0x109): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `f09(unsigned long)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f10(long long)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX:(.text+0x118): additional relocation overflows omitted from the output
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f11(unsigned long long)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f12(int*)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f13(int (*) [5])'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f14(int (*)(double))'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f15(int const*)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f16(int volatile*)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f17(int&)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f18(S*)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f19(T)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f20(E)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `f21(int T::*)'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `C::C()'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `C::mf()'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `c_func'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `SS<int>::SS()'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `c_var'
a.o:/cygdrive/d/home/khasegawa/lang/43_ISO_IEC_14882/28_cxx_label/a.s:XX: undefined reference to `C::~C()'
a.o:fake:(.rdata$.refptr._ZN3abc3def3ghiE[.refptr._ZN3abc3def3ghiE]+0x0): undefined reference to `abc::def::ghi'
collect2: error: ld returned 1 exit status
